name: gf_app
description: A GetWidget Demo App

version: 1.0.8+9

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  getwidget: ^1.1.3
  webview_flutter: ^0.3.19+6
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/image.png
    - lib/assets/images/image1.png
    - lib/assets/images/red.png
    - lib/assets/images/purple.png
    - lib/assets/images/pink.png
    - lib/assets/images/orange.png
    - lib/assets/images/image2.png
    - lib/assets/images/img.png
    - lib/assets/images/img1.png
    - lib/assets/images/img2.png
    - lib/assets/images/card.png
    - lib/assets/images/card1.png
    - lib/assets/images/card2.png
    - lib/assets/images/card3.png
    - lib/assets/images/card5.png
    - lib/assets/images/card4.png
    - lib/assets/images/gflogo.png
    - lib/assets/images/avatar1.png
    - lib/assets/images/avatar2.png
    - lib/assets/images/avatar3.png
    - lib/assets/images/avatar4.png
    - lib/assets/images/avatar5.png
    - lib/assets/images/avatar6.png
    - lib/assets/images/avatar7.png
    - lib/assets/images/avatar8.png
    - lib/assets/images/avatar9.png
    - lib/assets/images/avatar10.png
    - lib/assets/images/avatar11.png
    - lib/assets/images/avatar12.png
    - lib/assets/gif/success1.gif
    - lib/assets/icons/gflogo.png

  fonts:
    - family: GFFontIcons
      fonts:
        - asset: lib/assets/fonts/gfFontIcon.ttf
          weight: 400

    - family: GFFontIcons2
      fonts:
        - asset: lib/assets/fonts/gfFontIcons2.ttf
          weight: 400

    - family: GFSocialFonts
      fonts:
        - asset: lib/assets/fonts/gfSocialFonts.ttf
          weight: 400

    - family: GFIconFonts
      fonts:
        - asset: lib/assets/fonts/gfIconFonts.ttf
          weight: 400

    - family: GFIcons
      fonts:
        - asset: lib/assets/fonts/loader.ttf
          weight: 400
